{
 "title": "Cluster overview",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Global Ingress Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(shop_http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Control-Plane Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "up{job=~\".*apiserver.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total[1h])) by (namespace, pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Resource Pressure (Memory Usage %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}