apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop-operator.fullname" . }}-metrics
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "shop-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "shop-operator.selectorLabels" . | nindent 4 }}