apiVersion: v2
name: shophub
description: Helm chart for ShopHub (uses Shop CRDs + kube-prometheus-stack)
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - shophub
  - platform
  - multi-tenant
maintainers:
  - name: RisticDorde
  - name: 0101dusica
home: https://github.com/ShopHub-DevOps/shophub
sources:
  - https://github.com/ShopHub-DevOps/shophub
