apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shophub.fullname" . }}-discord-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shophub.labels" . | nindent 4 }}
type: Opaque
stringData:
  webhook-url: {{ .Values.alerting.discordWebhookUrl | quote }}
