apiVersion: v1
kind: Service
metadata:
  name: {{ include "shophub.fullname" . }}-frontend
  labels:
    {{- include "shophub.labels" . | nindent 4 }}
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "shophub.selectorLabels" . | nindent 4 }}
    component: frontend
    