apiVersion: v1
kind: Secret
metadata:
  name: shophub-grafana-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shophub.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: admin
  admin-password: {{ .Values.grafanaAdminPassword | quote }}
  github-client-id: {{ .Values.githubOAuth.clientId | quote }}
  github-client-secret: {{ .Values.githubOAuth.clientSecret | quote }}
