apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shophub.fullname" . }}-secrets
  labels:
    {{- include "shophub.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.jwtSecret | b64enc | quote }}