backendImage: ghcr.io/shophub-devops/shop-backend
backendTag: "1.0.0"
frontendImage: ghcr.io/shophub-devops/shop-frontend
frontendTag: "1.0.0"

availabilityTier: standard
replicasStandard: 2
replicasHigh: 3

ingressHostname: "shop-test.local"
databaseSecretName: "postgres-secret"
walletAddress: "0x742d35Cc6634C0532925a3b844Bc9e7595f42b9"

jwtSecret: "test-jwt-secret-32-characters-long!!"

env:
  NODE_ENV: production
  LOG_LEVEL: info