apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shop.fullname" . }}-config
  labels:
    {{- include "shop.labels" . | nindent 4 }}
data:
  BACKEND_URL: "http://{{ include "shop.fullname" . }}-backend:{{ .Values.backendPort }}"
  FRONTEND_URL: "http://{{ .Values.ingressHostname }}"
  WALLET_ADDRESS: {{ .Values.walletAddress | quote }}
