apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shop.fullname" . }}-secrets
  labels:
    {{- include "shop.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.jwtSecret | b64enc | quote }}
